const types = {
  MARK_TODO: 'MARK_TODO',
  CREATE_TODO: 'CREATE_TODO',
  ADD_PLAYERS: 'ADD_PLAYERS',
  DELETE_TODO: 'DELETE_TODO',
  MARK_CELL: 'MARK_CELL',
  LOOKUP: 'LOOKUP',
  LOOKUP_SUCCESS: 'LOOKUP_SUCCESS',
};

export default types;